"""Command-line interface for PyDoc2Markdown."""

import argparse
import logging
import sys
from pathlib import Path
from tempfile import TemporaryDirectory

from pydoc2markdown import __version__
from pydoc2markdown.core.config import load_config
from pydoc2markdown.core.generator import MarkdownGenerator
from pydoc2markdown.core.parser import DocstringParser, ModuleDoc
from pydoc2markdown.core.watcher import watch_and_generate

logger = logging.getLogger(__name__)

_DEFAULT_CONFIG = """[tool.pydoc2markdown]
output = "docs"
theme = "default"
recursive = true
"""

_DEMO_FILES = {
    "src/shop_demo/__init__.py": '''"""Small shop demo package for PyDoc2Markdown examples."""

from shop_demo.inventory import Inventory, Product
from shop_demo.orders import Order, OrderStatus, calculate_total

__all__ = [
    "Inventory",
    "Order",
    "OrderStatus",
    "Product",
    "calculate_total",
]
''',
    "src/shop_demo/inventory.py": '''"""Inventory models and helpers for the sample shop."""

from dataclasses import dataclass


@dataclass
class Product:
    """A product available in the shop.

    Args:
        sku: Stable product identifier.
        name: Human-readable product name.
        price: Unit price in the shop currency.
        stock: Number of available units.
    """

    sku: str
    name: str
    price: float
    stock: int = 0

    @property
    def available(self) -> bool:
        """Whether the product can be purchased."""
        return self.stock > 0


class Inventory:
    """In-memory product inventory.

    Args:
        products: Initial products keyed by SKU.
    """

    def __init__(self, products: dict[str, Product] | None = None) -> None:
        self._products = products or {}

    def add(self, product: Product) -> None:
        """Add or replace a product.

        Args:
            product: Product to store.
        """
        self._products[product.sku] = product

    def get(self, sku: str) -> Product:
        """Return a product by SKU.

        Args:
            sku: Product identifier.

        Returns:
            Matching product.

        Raises:
            KeyError: If the SKU is unknown.
        """
        return self._products[sku]
''',
    "src/shop_demo/orders.py": '''"""Order models and pricing helpers."""

from dataclasses import dataclass
from enum import Enum

from shop_demo.inventory import Product


class OrderStatus(Enum):
    """Lifecycle status for an order."""

    DRAFT = "draft"
    PAID = "paid"
    SHIPPED = "shipped"


@dataclass
class Order:
    """A customer order.

    Args:
        order_id: Public order identifier.
        items: Products included in the order.
        status: Current order status.
    """

    order_id: str
    items: list[Product]
    status: OrderStatus = OrderStatus.DRAFT

    def mark_paid(self) -> None:
        """Mark the order as paid."""
        self.status = OrderStatus.PAID


def calculate_total(items: list[Product], discount: float = 0.0) -> float:
    """Calculate the discounted order total.

    Args:
        items: Products to include in the total.
        discount: Discount ratio between 0 and 1.

    Returns:
        Total price after discount.

    Raises:
        ValueError: If discount is outside the accepted range.
    """
    if not 0 <= discount <= 1:
        raise ValueError("discount must be between 0 and 1")
    subtotal = sum(item.price for item in items)
    return subtotal * (1 - discount)
''',
    "README.md": """# PyDoc2Markdown Demo

Small demo project generated by `pydoc2markdown --demo`.

## API Reference

<!-- pydoc2markdown:start -->
<!-- pydoc2markdown:end -->
""",
}


def create_parser() -> argparse.ArgumentParser:
    """Create and configure the argument parser."""
    defaults = load_config()
    parser = argparse.ArgumentParser(
        prog="pydoc2markdown",
        description=(
            "Convert Python docstrings into Markdown docs, README API sections, "
            "or a navigation-ready docs layout."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  pydoc2markdown src/my_package --recursive -o docs
  pydoc2markdown src/my_package --recursive --nav -o docs
  pydoc2markdown src/my_package --recursive --readme
  pydoc2markdown --demo
  pydoc2markdown --init
""",
    )
    input_group = parser.add_argument_group("Input")
    output_group = parser.add_argument_group("Output")
    readme_group = parser.add_argument_group("README integration")
    config_group = parser.add_argument_group("Configuration")
    demo_group = parser.add_argument_group("Demo")
    watch_group = parser.add_argument_group("Watch mode")
    logging_group = parser.add_argument_group("Logging")

    input_group.add_argument(
        "source",
        type=Path,
        nargs="?",
        help="Path to a Python file or directory to process.",
    )
    input_group.add_argument(
        "--recursive",
        action="store_true",
        default=defaults.get("recursive", False),
        help="Recursively process subdirectories.",
    )
    config_group.add_argument(
        "--init",
        action="store_true",
        default=False,
        help="Create or update [tool.pydoc2markdown] in pyproject.toml.",
    )
    config_group.add_argument(
        "--template",
        type=Path,
        default=None,
        help="Path to a custom Jinja2 template for Markdown generation.",
    )
    config_group.add_argument(
        "--theme",
        choices=["default", "minimal"],
        default=defaults.get("theme", "default"),
        help="Built-in theme/template to use (default: default).",
    )
    demo_group.add_argument(
        "--demo",
        action="store_true",
        default=False,
        help="Create a small demo project and generate docs for it.",
    )
    demo_group.add_argument(
        "--demo-output",
        type=Path,
        default=Path("pydoc2markdown-demo"),
        help="Directory created by --demo.",
    )
    output_group.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path(str(defaults.get("output", "docs"))),
        help="Output directory (or file when --single-file is used).",
    )
    output_group.add_argument(
        "--single-file",
        action="store_true",
        default=False,
        help="Generate a single combined Markdown file instead of separate files.",
    )
    output_group.add_argument(
        "--nav",
        action="store_true",
        default=False,
        help="Generate a navigation-first docs layout with API pages under api/.",
    )
    output_group.add_argument(
        "--check",
        action="store_true",
        default=False,
        help="Check whether generated docs are up to date without writing files.",
    )
    output_group.add_argument(
        "--api-dir",
        type=Path,
        default=Path("api"),
        help="Directory for API pages when --nav is used.",
    )
    readme_group.add_argument(
        "--readme",
        action="store_true",
        default=False,
        help="Create or update an API reference section in README.md.",
    )
    readme_group.add_argument(
        "--readme-path",
        type=Path,
        default=Path("README.md"),
        help="Path to the README file updated by --readme.",
    )
    watch_group.add_argument(
        "--watch",
        action="store_true",
        help="Watch source files and regenerate docs on change.",
    )
    logging_group.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help="Increase verbosity (-v for INFO, -vv for DEBUG).",
    )
    logging_group.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    return parser


def _setup_logging(verbosity: int) -> None:
    """Configure logging level based on verbosity count."""
    level = logging.WARNING
    if verbosity >= 2:
        level = logging.DEBUG
    elif verbosity == 1:
        level = logging.INFO
    logging.basicConfig(
        level=level,
        format="%(name)s - %(levelname)s - %(message)s",
    )


def _log_cli_error(message: str, *, hint: str | None = None) -> int:
    """Log a user-facing CLI error and optional next step."""
    logger.error(message)
    if hint:
        logger.error("Hint: %s", hint)
    return 1


def init_config() -> int:
    """Create or update [tool.pydoc2markdown] in pyproject.toml.

    Returns:
        0 on success, 1 on error.
    """
    try:
        import tomllib
    except ModuleNotFoundError:
        import tomli as tomllib

    pyproject = Path.cwd() / "pyproject.toml"

    if not pyproject.exists():
        # Create minimal pyproject.toml with just our section
        pyproject.write_text(_DEFAULT_CONFIG, encoding="utf-8")
        logger.info("Created pyproject.toml with [tool.pydoc2markdown] defaults.")
        return 0

    # File exists — parse it
    try:
        with pyproject.open("rb") as f:
            data = tomllib.load(f)
    except Exception:
        logger.error("Failed to parse pyproject.toml — file exists but is not valid TOML.")
        return 1

    # Check if section already exists
    if "tool" in data and "pydoc2markdown" in data["tool"]:
        logger.info(
            "[tool.pydoc2markdown] already exists in pyproject.toml — nothing to change. "
            "Edit it manually if you want to override defaults."
        )
        return 0

    # Section doesn't exist — append it
    existing = pyproject.read_text(encoding="utf-8")
    if existing and not existing.endswith("\n"):
        existing += "\n"
    existing += "\n" + _DEFAULT_CONFIG
    pyproject.write_text(existing, encoding="utf-8")
    logger.info("Added [tool.pydoc2markdown] to existing pyproject.toml.")
    return 0


def run_demo(output_dir: Path) -> int:
    """Create a demo project and generate documentation for it."""
    if output_dir.exists() and any(output_dir.iterdir()):
        return _log_cli_error(
            f"Demo output directory is not empty: {output_dir}",
            hint="Choose another directory with --demo-output, or remove the existing directory.",
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    for relative_path, content in _DEMO_FILES.items():
        path = output_dir / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    source = output_dir / "src"
    docs = output_dir / "docs"
    readme = output_dir / "README.md"

    modules = DocstringParser().parse(source, recursive=True)
    generator = MarkdownGenerator()
    generated = generator.generate_navigation(modules, docs)
    generator.update_readme(modules, readme)

    print(f"Created demo project: {output_dir}")
    print(f"Generated {len(generated)} docs file(s): {docs}")
    print(f"Updated README API section: {readme}")
    print(f"Open docs index: {docs / 'index.md'}")
    return 0


def _different_files(
    expected_dir: Path,
    actual_dir: Path,
    expected_paths: list[Path],
) -> list[Path]:
    """Return generated files whose current output is missing or outdated."""
    different: list[Path] = []
    for expected_path in expected_paths:
        relative_path = expected_path.relative_to(expected_dir)
        actual_path = actual_dir / relative_path
        if not actual_path.exists():
            different.append(actual_path)
            continue
        if expected_path.read_text(encoding="utf-8") != actual_path.read_text(encoding="utf-8"):
            different.append(actual_path)
    return different


def _check_readme(
    generator: MarkdownGenerator,
    modules: list[ModuleDoc],
    readme_path: Path,
    temp_dir: Path,
) -> list[Path]:
    """Return README path when its generated API section is missing or outdated."""
    expected_readme = temp_dir / "README.md"
    if readme_path.exists():
        expected_readme.write_text(readme_path.read_text(encoding="utf-8"), encoding="utf-8")

    generator.update_readme(modules, expected_readme)
    if not readme_path.exists():
        return [readme_path]
    if expected_readme.read_text(encoding="utf-8") != readme_path.read_text(encoding="utf-8"):
        return [readme_path]
    return []


def check_generated_docs(
    generator: MarkdownGenerator,
    modules: list[ModuleDoc],
    *,
    output: Path,
    single_file: bool,
    readme: bool,
    readme_path: Path,
    navigation: bool,
    api_dir: Path,
) -> int:
    """Check whether generated documentation matches the current files."""
    with TemporaryDirectory() as temp_name:
        temp_dir = Path(temp_name)
        stale_paths: list[Path] = []

        if single_file:
            expected_output = temp_dir / output.name
            generator.generate_single_file(modules, expected_output)
            if not output.exists() or (
                expected_output.read_text(encoding="utf-8") != output.read_text(encoding="utf-8")
            ):
                stale_paths.append(output)
        elif navigation:
            expected_output_dir = temp_dir / "docs"
            expected_paths = generator.generate_navigation(
                modules,
                expected_output_dir,
                api_dir=api_dir,
            )
            stale_paths.extend(_different_files(expected_output_dir, output, expected_paths))
        else:
            expected_output_dir = temp_dir / "docs"
            expected_paths = generator.generate(modules, expected_output_dir)
            stale_paths.extend(_different_files(expected_output_dir, output, expected_paths))

        if readme:
            try:
                stale_paths.extend(_check_readme(generator, modules, readme_path, temp_dir))
            except ValueError as exc:
                return _log_cli_error(
                    str(exc),
                    hint=(
                        "Keep both <!-- pydoc2markdown:start --> and "
                        "<!-- pydoc2markdown:end --> in the README, or remove both markers."
                    ),
                )

    if stale_paths:
        logger.error("Generated documentation is out of date.")
        for path in stale_paths:
            logger.error("Outdated: %s", path)
        logger.error("Run the same command without --check to update generated files.")
        return 1

    logger.info("Generated documentation is up to date.")
    return 0


def main(args: list[str] | None = None) -> int:
    """Main entry point for the CLI."""
    parser = create_parser()
    parsed_args = parser.parse_args(args)
    _setup_logging(parsed_args.verbose)

    if parsed_args.init:
        return init_config()

    if parsed_args.demo:
        if parsed_args.source is not None:
            return _log_cli_error(
                "--demo does not accept a source path.",
                hint="Run 'pydoc2markdown --demo', or remove --demo to process your own source.",
            )
        return run_demo(parsed_args.demo_output)

    if parsed_args.source is None:
        return _log_cli_error(
            "Missing source path.",
            hint="Run 'pydoc2markdown --help' for examples, or use '--init' to create config.",
        )

    if not parsed_args.source.exists():
        return _log_cli_error(
            f"Source path does not exist: {parsed_args.source}",
            hint=(
                "Pass a Python file or package directory, for example: "
                "pydoc2markdown src --recursive -o docs"
            ),
        )

    if parsed_args.nav and parsed_args.single_file:
        return _log_cli_error(
            "--nav cannot be combined with --single-file.",
            hint="Use --nav for a docs directory, or --single-file for one combined Markdown file.",
        )

    if parsed_args.check and parsed_args.watch:
        return _log_cli_error(
            "--check cannot be combined with --watch.",
            hint="Use --check in CI, or --watch while editing locally.",
        )

    if parsed_args.watch:
        return watch_and_generate(
            source=parsed_args.source,
            output_dir=parsed_args.output,
            recursive=parsed_args.recursive,
            theme=parsed_args.theme,
            template_path=parsed_args.template,
            single_file=parsed_args.single_file,
            readme_path=parsed_args.readme_path if parsed_args.readme else None,
            navigation=parsed_args.nav,
            api_dir=parsed_args.api_dir,
        )

    logger.info("Parsing source: %s (recursive=%s)", parsed_args.source, parsed_args.recursive)
    doc_parser = DocstringParser()
    md_generator = MarkdownGenerator(
        template_path=parsed_args.template,
        theme=parsed_args.theme,
    )

    try:
        modules = doc_parser.parse(
            source=parsed_args.source,
            recursive=parsed_args.recursive,
        )
        logger.info("Parsed %d module(s)", len(modules))
        if parsed_args.check:
            return check_generated_docs(
                md_generator,
                modules,
                output=parsed_args.output,
                single_file=parsed_args.single_file,
                readme=parsed_args.readme,
                readme_path=parsed_args.readme_path,
                navigation=parsed_args.nav,
                api_dir=parsed_args.api_dir,
            )
        if parsed_args.single_file:
            single_path = md_generator.generate_single_file(
                modules=modules,
                output_path=parsed_args.output,
            )
            logger.info("Generated single Markdown file: %s", single_path)
        elif parsed_args.nav:
            generated = md_generator.generate_navigation(
                modules=modules,
                output_dir=parsed_args.output,
                api_dir=parsed_args.api_dir,
            )
            logger.info(
                "Generated %d navigation docs file(s) in %s",
                len(generated),
                parsed_args.output,
            )
        else:
            generated = md_generator.generate(
                modules=modules,
                output_dir=parsed_args.output,
            )
            logger.info("Generated %d Markdown file(s) in %s", len(generated), parsed_args.output)
        if parsed_args.readme:
            try:
                readme_path = md_generator.update_readme(
                    modules=modules,
                    readme_path=parsed_args.readme_path,
                )
            except ValueError as exc:
                return _log_cli_error(
                    str(exc),
                    hint=(
                        "Keep both <!-- pydoc2markdown:start --> and "
                        "<!-- pydoc2markdown:end --> in the README, or remove both markers."
                    ),
                )
            logger.info("Updated README API reference: %s", readme_path)
    except Exception:
        logger.exception("Documentation generation failed")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
